// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package mariadb

import (
	"context"
)

type Querier interface {
	GetProductByKode(ctx context.Context, kodeProduk string) (MProduk, error)
	ListProduk(ctx context.Context) ([]MProduk, error)
}

var _ Querier = (*Queries)(nil)
